description: mnist_pytorch_distributed
data:
  url: https://s3-us-west-2.amazonaws.com/determined-ai-test-data/pytorch_mnist.tar.gz
hyperparameters:
  learning_rate: 1.0
  global_batch_size: 512
  n_filters1: 32
  n_filters2: 64
  dropout1: 0.25
  dropout2: 0.5
resources:
  resource_pool: cpu-pool
  slots_per_trial: 2
max_restarts: 0
searcher:
  name: single
  metric: validation_loss
  max_length:
      batches: 117  #60,000 training images with batch size 512 (batch size 64 per GPU)
  smaller_is_better: true
entrypoint: model_def:MNistTrial
environment:
  image: determinedilia/environments:py-3.7-pytorch-1.7-tf-1.15-cpu-08130e8
  #debug: true
