description: cifar10_tf_keras_distributed
data:
  url: https://s3-us-west-2.amazonaws.com/determined-ai-datasets/cifar10/cifar-10-python.tar.gz
hyperparameters:
  learning_rate: 1e-4
  learning_rate_decay: 1e-6
  layer1_dropout: 0.25
  layer2_dropout: 0.25
  layer3_dropout: 0.5
  global_batch_size: 512
  width_shift_range: 0.1
  height_shift_range: 0.1
  horizontal_flip: True
records_per_epoch: 50000
resources:
  resource_pool: cpu-pool
  slots_per_trial: 4
searcher:
  name: single
  metric: val_categorical_error
  max_length:
    epochs: 32
min_validation_period:
  epochs: 1
entrypoint: model_def:CIFARTrial
environment:
  image: determinedilia/environments:py-3.7-pytorch-1.7-tf-1.15-cpu-08130e8
